# Generated by Django 2.1.5 on 2021-11-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='files/')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eje', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Titulo')),
            ],
        ),
        migrations.AddField(
            model_name='descripcion',
            name='eje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conhechos.Eje'),
        ),
    ]
