# Generated by Django 2.1.5 on 2021-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conhechos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumplimosLoPrometidoVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SliderVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
