# Generated by Django 2.1.5 on 2021-11-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conhechos', '0002_cumplimosloprometidovideo_slidervideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CumplimosLoPrometidoVideo',
        ),
        migrations.DeleteModel(
            name='SliderVideo',
        ),
    ]
